version: "3.8"

services:
  db:
    image: mysql:8.4
    volumes:
      - ./mysql:/var/lib/mysql
      - ./backend/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=verysecurepassword
      - MYSQL_DATABASE=contact_agence

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - PMA_HOST=db
